/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package P1.vista;

import java.io.IOException;
import java.math.BigInteger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import P1.logica.Controlador;

/**
 *
 * @author marco
 */
public class CarcasaCliente extends javax.swing.JFrame {
    
    private Controlador monitor;
    private int CuentaUsuario;

    /**
     * Creates new form CarcasaCliente
     */
    public CarcasaCliente() {
        try {
            monitor = new Controlador();
            new Thread(monitor).start();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, 
                    "No se puede iniciar la aplicacion:\n"
                    + "Problemas en la conexion con el servidor\n" + e.getMessage(),
                    "---- ERROR ----",
                    JOptionPane.ERROR_MESSAGE);
            //Runtime.getRuntime().exit(1);
        }
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpContenedor = new javax.swing.JDesktopPane();
        jifLogin = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jtfPassword = new javax.swing.JTextField();
        jbIniciarSesion = new javax.swing.JButton();
        jifDepositos = new javax.swing.JInternalFrame();
        jLabel4 = new javax.swing.JLabel();
        jtfCantidadDepositada = new javax.swing.JTextField();
        jbOKDeposito = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jifRetiros = new javax.swing.JInternalFrame();
        jLabel5 = new javax.swing.JLabel();
        jtfCantidadRetirada = new javax.swing.JTextField();
        jbOKRetiro = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jifConsultas = new javax.swing.JInternalFrame();
        jLabel3 = new javax.swing.JLabel();
        jtfCantidadBalance = new javax.swing.JTextField();
        jbAceptarSaldo = new javax.swing.JButton();
        jifTransferencias = new javax.swing.JInternalFrame();
        jLabel6 = new javax.swing.JLabel();
        jtfIdCuentaDestino = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfCantidadTransferida = new javax.swing.JTextField();
        jbTransferir = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jmiInvalidarSesion = new javax.swing.JMenuItem();
        jmiSalir = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        jmiConsulta = new javax.swing.JMenuItem();
        jmiRetiro = new javax.swing.JMenuItem();
        jmiDeposito = new javax.swing.JMenuItem();
        jmiTransferencia = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Honorable Banco de San Pedro de los Saguaros");

        jifLogin.setVisible(true);

        jLabel1.setText("Usuario");

        jLabel2.setText("Password");

        jbIniciarSesion.setText("Iniciar sesion");
        jbIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIniciarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jifLoginLayout = new javax.swing.GroupLayout(jifLogin.getContentPane());
        jifLogin.getContentPane().setLayout(jifLoginLayout);
        jifLoginLayout.setHorizontalGroup(
            jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifLoginLayout.createSequentialGroup()
                .addGroup(jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jifLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jifLoginLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jifLoginLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jtfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jifLoginLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jbIniciarSesion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jifLoginLayout.setVerticalGroup(
            jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbIniciarSesion)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jdpContenedor.add(jifLogin);
        jifLogin.setBounds(200, 180, 260, 180);

        jifDepositos.setVisible(false);

        jLabel4.setText("Digite la cantidad a depositar");

        jbOKDeposito.setText("Aceptar");
        jbOKDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOKDepositoActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");

        javax.swing.GroupLayout jifDepositosLayout = new javax.swing.GroupLayout(jifDepositos.getContentPane());
        jifDepositos.getContentPane().setLayout(jifDepositosLayout);
        jifDepositosLayout.setHorizontalGroup(
            jifDepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifDepositosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jifDepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfCantidadDepositada)
                    .addGroup(jifDepositosLayout.createSequentialGroup()
                        .addComponent(jbOKDeposito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jifDepositosLayout.setVerticalGroup(
            jifDepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifDepositosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jtfCantidadDepositada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jifDepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbOKDeposito)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jdpContenedor.add(jifDepositos);
        jifDepositos.setBounds(0, 0, 520, 310);

        jifRetiros.setVisible(false);

        jLabel5.setText("Digite la cantidad a depositar");

        jbOKRetiro.setText("Aceptar");
        jbOKRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOKRetiroActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");

        javax.swing.GroupLayout jifRetirosLayout = new javax.swing.GroupLayout(jifRetiros.getContentPane());
        jifRetiros.getContentPane().setLayout(jifRetirosLayout);
        jifRetirosLayout.setHorizontalGroup(
            jifRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifRetirosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jifRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfCantidadRetirada)
                    .addGroup(jifRetirosLayout.createSequentialGroup()
                        .addComponent(jbOKRetiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jifRetirosLayout.setVerticalGroup(
            jifRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifRetirosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jtfCantidadRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jifRetirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbOKRetiro)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jdpContenedor.add(jifRetiros);
        jifRetiros.setBounds(0, 0, 520, 310);

        jifConsultas.setVisible(false);

        jLabel3.setText("Balance");

        jtfCantidadBalance.setEditable(false);
        jtfCantidadBalance.setText("$ 0");

        jbAceptarSaldo.setText("Aceptar");

        javax.swing.GroupLayout jifConsultasLayout = new javax.swing.GroupLayout(jifConsultas.getContentPane());
        jifConsultas.getContentPane().setLayout(jifConsultasLayout);
        jifConsultasLayout.setHorizontalGroup(
            jifConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifConsultasLayout.createSequentialGroup()
                .addGroup(jifConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jifConsultasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jtfCantidadBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jifConsultasLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jbAceptarSaldo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jifConsultasLayout.setVerticalGroup(
            jifConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifConsultasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jifConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfCantidadBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbAceptarSaldo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jdpContenedor.add(jifConsultas);
        jifConsultas.setBounds(0, 0, 520, 310);

        jifTransferencias.setVisible(false);

        jLabel6.setText("# de Cuenta de destino");

        jLabel7.setText("Cantidad a transferir");

        jbTransferir.setText("Transferir");
        jbTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTransferirActionPerformed(evt);
            }
        });

        jButton5.setText("Cancelar");

        javax.swing.GroupLayout jifTransferenciasLayout = new javax.swing.GroupLayout(jifTransferencias.getContentPane());
        jifTransferencias.getContentPane().setLayout(jifTransferenciasLayout);
        jifTransferenciasLayout.setHorizontalGroup(
            jifTransferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifTransferenciasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jifTransferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jifTransferenciasLayout.createSequentialGroup()
                        .addComponent(jbTransferir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jifTransferenciasLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(26, 26, 26)
                        .addComponent(jtfIdCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jifTransferenciasLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfCantidadTransferida, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jifTransferenciasLayout.setVerticalGroup(
            jifTransferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifTransferenciasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jifTransferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfIdCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jifTransferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfCantidadTransferida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jifTransferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jbTransferir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jdpContenedor.add(jifTransferencias);
        jifTransferencias.setBounds(0, 0, 520, 310);

        fileMenu.setMnemonic('A');
        fileMenu.setText("Archivo");

        jmiInvalidarSesion.setText("Cerrar sesion");
        jmiInvalidarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInvalidarSesionActionPerformed(evt);
            }
        });
        fileMenu.add(jmiInvalidarSesion);

        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        fileMenu.add(jmiSalir);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('O');
        editMenu.setText("Operaciones");

        jmiConsulta.setMnemonic('t');
        jmiConsulta.setText("Consulta de saldo");
        jmiConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultaActionPerformed(evt);
            }
        });
        editMenu.add(jmiConsulta);

        jmiRetiro.setMnemonic('y');
        jmiRetiro.setText("Retiro de efectivo");
        jmiRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRetiroActionPerformed(evt);
            }
        });
        editMenu.add(jmiRetiro);

        jmiDeposito.setMnemonic('p');
        jmiDeposito.setText("Deposito de efectivo");
        jmiDeposito.setToolTipText("");
        jmiDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDepositoActionPerformed(evt);
            }
        });
        editMenu.add(jmiDeposito);

        jmiTransferencia.setMnemonic('d');
        jmiTransferencia.setText("Transferencia");
        jmiTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTransferenciaActionPerformed(evt);
            }
        });
        editMenu.add(jmiTransferencia);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('H');
        helpMenu.setText("Ayuda");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Acerca de");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        Runtime.getRuntime().exit(0);
    }//GEN-LAST:event_jmiSalirActionPerformed

    private void jbIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIniciarSesionActionPerformed
        boolean confirmado = false;
        try {
            confirmado = monitor.iniciaSesion(jtfUsuario.getText(), jtfPassword.getText());
            this.CuentaUsuario = Integer.parseInt(jtfUsuario.getText());
            if (confirmado) {
                JOptionPane.showMessageDialog(this, 
                        "Listo, ha iniciado sesion",
                        "---- OK ----",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, 
                        "Este usuario no esta registrado para usar el servicio",
                        "---- ALERTA ----",
                        JOptionPane.WARNING_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                    "Problemas con la autenticacion del usuario\n" + e.getMessage(),
                    "---- ERROR ----",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbIniciarSesionActionPerformed

    private void jmiConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultaActionPerformed
        cerrarVentanitas();
        double saldo = 0;
        try {
            saldo = monitor.consultar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                    "Problemas al obtener el balance del usuario\n" + e.getMessage(),
                    "---- ERROR ----",
                    JOptionPane.ERROR_MESSAGE);
        }
        
        jtfCantidadBalance.setText("$ " + saldo);
        jifConsultas.setVisible(true);
        
    }//GEN-LAST:event_jmiConsultaActionPerformed

    private void jmiRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRetiroActionPerformed
        cerrarVentanitas();
        jifRetiros.setVisible(true);
    }//GEN-LAST:event_jmiRetiroActionPerformed

    private void jmiDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDepositoActionPerformed
        cerrarVentanitas();
        jifDepositos.setVisible(true);
    }//GEN-LAST:event_jmiDepositoActionPerformed

    private void jmiTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTransferenciaActionPerformed
        cerrarVentanitas();
        jifTransferencias.setVisible(true);
    }//GEN-LAST:event_jmiTransferenciaActionPerformed

    private void jbOKRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOKRetiroActionPerformed
        boolean retirado = false;
        try {
            retirado = monitor.retirar(new Double(jtfCantidadRetirada.getText()));
            
            if (retirado) {
                JOptionPane.showMessageDialog(this, 
                        "Listo, la cantidad ha sido retirada",
                        "---- OK ----",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, 
                        "No se puede retirar esta cantidad",
                        "---- ALERTA ----",
                        JOptionPane.WARNING_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                    "Problemas en el retiro de dinero\n" + e.getMessage(),
                    "---- ERROR ----",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbOKRetiroActionPerformed

    private void jbOKDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOKDepositoActionPerformed
        boolean depositado = false;
        try {
            depositado = monitor.depositar(new Double(jtfCantidadDepositada.getText()));
            
            if (depositado) {
                JOptionPane.showMessageDialog(this, 
                        "Listo, la cantidad ha sido depositada",
                        "---- OK ----",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, 
                        "No se puede depositar esta cantidad",
                        "---- ALERTA ----",
                        JOptionPane.WARNING_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                    "Problemas en el deposito de dinero\n" + e.getMessage(),
                    "---- ERROR ----",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbOKDepositoActionPerformed

    private void jbTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTransferirActionPerformed
        boolean transferido = false;
        try {
            transferido = monitor.transferir(new BigInteger(jtfIdCuentaDestino.getText()),
                    new Double(jtfCantidadTransferida.getText()));
            
            if (transferido) {
                JOptionPane.showMessageDialog(this, 
                        "Listo, se realizo la transferencia",
                        "---- OK ----",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, 
                        "No se puede realizar esta transferencia",
                        "---- ALERTA ----",
                        JOptionPane.WARNING_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                    "Problemas con la tranferencia de dinero entre cuentas\n" + e.getMessage(),
                    "---- ERROR ----",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbTransferirActionPerformed

    private void jmiInvalidarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInvalidarSesionActionPerformed
        
    }//GEN-LAST:event_jmiInvalidarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarcasaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarcasaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarcasaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarcasaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarcasaCliente().setVisible(true);
            }
        });
    }
    
    private void cerrarVentanitas(){
        for (JInternalFrame jif : jdpContenedor.getAllFrames()) {
            jif.setVisible(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbAceptarSaldo;
    private javax.swing.JButton jbIniciarSesion;
    private javax.swing.JButton jbOKDeposito;
    private javax.swing.JButton jbOKRetiro;
    private javax.swing.JButton jbTransferir;
    private javax.swing.JDesktopPane jdpContenedor;
    private javax.swing.JInternalFrame jifConsultas;
    private javax.swing.JInternalFrame jifDepositos;
    private javax.swing.JInternalFrame jifLogin;
    private javax.swing.JInternalFrame jifRetiros;
    private javax.swing.JInternalFrame jifTransferencias;
    private javax.swing.JMenuItem jmiConsulta;
    private javax.swing.JMenuItem jmiDeposito;
    private javax.swing.JMenuItem jmiInvalidarSesion;
    private javax.swing.JMenuItem jmiRetiro;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JMenuItem jmiTransferencia;
    private javax.swing.JTextField jtfCantidadBalance;
    private javax.swing.JTextField jtfCantidadDepositada;
    private javax.swing.JTextField jtfCantidadRetirada;
    private javax.swing.JTextField jtfCantidadTransferida;
    private javax.swing.JTextField jtfIdCuentaDestino;
    private javax.swing.JTextField jtfPassword;
    private javax.swing.JTextField jtfUsuario;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
